baseurl = "https://dtjm.github.io/"
languageCode = "en-us"
theme = "hyde"
title = "Sam X."
publishdir = "."
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
description = "Software engineer at SendGrid writes about Go programming and more."
themeColor = "theme-base-0d"
