baseurl = "http://samx.io/"
languageCode = "en-us"
theme = "hyde"
title = "Sam X."
publishdir = "."
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
description = "Software engineer at Twilio SendGrid writes about Go programming and more."
disqusShortname = "samx-io"
themeColor = "theme-base-0d"
